spring.application.name=kafka-producer

server.port=8080

# the only property needed to send message from producer
spring.kafka.bootstrap-servers=localhost:9092,localhost:9192

# Refresh producer metadata after 5 minutes if it has not been refreshed
spring.kafka.producer.properties.metadata.max.age.ms=300000

spring.kafka.producer.acks=all

# although this is always true in kafka version >= 3.0
spring.kafka.producer.properties.enable.idempotence=true

# key-serializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

# value-serializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# by-default it's true only, in segment logs it's visible as headerKeys: [__TYpeId__]
spring.kafka.producer.properties.spring.json.add.type.headers=true
# spring.kafka.producer.value-serializer=com.bsharan.kafka_order_producerducer.serializer.OrderSerializer

# after this much time, even if the batches are not fully filled, the message will be sent
spring.kafka.producer.properties.linger.ms=1000

# 1 Kb - max batch size for a single batch
spring.kafka.producer.properties.batch.size=1024

# 1Mb - combined batch-size
spring.kafka.producer.properties.buffer.memory=1048576

# if buffer size is full, it will wait this much time before failing the .send(...)
spring.kafka.producer.properties.max.block.ms=60000

# compression
spring.kafka.producer.properties.compression.type=snappy

# sender thread (retry on transient failures like - network timeout, leader change etc.)
spring.kafka.producer.retries=3

# max request at the same time without receiving any ack from broker
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

# this id should be unique to all instances that are running, also it should remain same even after application restart
# spring.kafka.producer.transaction-id-prefix=order-serv-${HOSTNAME}-
# it's also present by default
# spring.kafka.producer.properties.transaction.timeout.ms=60000

# enable for deeper logs
#logging.level.org.apache.kafka.clients.producer=DEBUG
#logging.level.org.apache.kafka.clients.producer.internals=TRACE

logging.level.org.apache.kafka.clients.producer=DEBUG
logging.level.org.apache.kafka.clients.producer.internals=TRACE
logging.level.org.apache.kafka.common.config.AbstractConfig=WARN
